// Generated by CoffeeScript 1.3.3
(function() {
  var Context,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Context = (function() {

    function Context() {
      this.get = __bind(this.get, this);

      this.set = __bind(this.set, this);
      this.symbol_table = {};
    }

    Context.prototype.set = function(symbol, value) {
      return this.symbol_table[symbol] = value;
    };

    Context.prototype.get = function(symbol) {
      return this.symbol_table[symbol];
    };

    return Context;

  })();

  module.exports = Context;

}).call(this);
