// Generated by CoffeeScript 1.3.3
(function() {
  var Context, SymbolTable,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  SymbolTable = (function() {

    function SymbolTable() {
      this.toJSON = __bind(this.toJSON, this);

      this.get = __bind(this.get, this);

      this.set = __bind(this.set, this);
      this.symbol_table = {};
    }

    SymbolTable.prototype.set = function(symbol, value) {
      return this.symbol_table[symbol] = value;
    };

    SymbolTable.prototype.get = function(symbol) {
      return this.symbol_table[symbol];
    };

    SymbolTable.prototype.toJSON = function() {
      return this.symbol_table;
    };

    return SymbolTable;

  })();

  Context = (function() {

    function Context() {
      this.toJSON = __bind(this.toJSON, this);
      this["public"] = new SymbolTable;
      this["private"] = new SymbolTable;
    }

    Context.prototype.toJSON = function() {
      return this["public"].toJSON();
    };

    return Context;

  })();

  module.exports = Context;

}).call(this);
