// Generated by CoffeeScript 1.3.3
(function() {
  var Evaluator, ImtoError, RuntimeError,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  ImtoError = require('./utils').ImtoError;

  RuntimeError = (function(_super) {

    __extends(RuntimeError, _super);

    function RuntimeError() {
      return RuntimeError.__super__.constructor.apply(this, arguments);
    }

    return RuntimeError;

  })(ImtoError);

  module.exports = Evaluator = (function() {

    function Evaluator(context) {
      this.context = context;
      this.number = __bind(this.number, this);

      this.operator = __bind(this.operator, this);

      this.block = __bind(this.block, this);

      this["function"] = __bind(this["function"], this);

      this.execute = __bind(this.execute, this);

      this.hash_assignment = __bind(this.hash_assignment, this);

      this.assignment = __bind(this.assignment, this);

      this.exec = __bind(this.exec, this);

      this.run = __bind(this.run, this);

    }

    Evaluator.prototype.run = function(parser) {
      var last;
      last = void 0;
      while (parser.peek() != null) {
        if (parser.peek().type === "comment") {
          parser.next();
        }
        last = this.exec(parser.next());
      }
      return last;
    };

    Evaluator.prototype.exec = function(node) {
      return this.assignment(node) || this.hash_assignment(node) || this.execute(node) || this["function"](node) || this.block(node) || this.operator(node) || this.number(node);
    };

    Evaluator.prototype.assignment = function(node) {
      if (node.type === "assignment") {
        return this.context["private"].set(node.symbol, this.exec(node.value));
      }
    };

    Evaluator.prototype.hash_assignment = function(node) {
      if (node.type === "hash_assignment") {
        this.context["public"].set(node.symbol, this.exec(node.value));
        return this.context.toJSON();
      }
    };

    Evaluator.prototype.execute = function(node) {
      var res;
      if (node.type === "execute") {
        res = this.context["public"].get(node.symbol);
        if (!res) {
          res = this.context["private"].get(node.symbol);
        }
        if (!res) {
          throw new RuntimeError("Undefined variable: " + node.symbol, {
            tracking: node.tracking.start
          });
        }
        if (res.type === "function") {
          res = this.exec(res.body);
        }
        return res;
      }
    };

    Evaluator.prototype["function"] = function(node) {
      if (node.type === "function") {
        return node;
      }
    };

    Evaluator.prototype.block = function(node) {
      if (node.type === "block") {
        return this.run(node.parse());
      }
    };

    Evaluator.prototype.operator = function(node) {
      if (node.type === "operator") {
        if (node.operator === "+") {
          return this.exec(node.left) + this.exec(node.right);
        }
        if (node.operator === "-") {
          return this.exec(node.left) - this.exec(node.right);
        }
      }
    };

    Evaluator.prototype.number = function(node) {
      if (node.type === "number") {
        return node.value;
      }
    };

    return Evaluator;

  })();

}).call(this);
