// Generated by CoffeeScript 1.3.3
(function() {
  var Context, Evaluator, Interpreter, Lexer, Parser;

  Lexer = require('./lexer');

  Parser = require('./parser');

  Context = require('./context');

  Evaluator = require('./evaluator');

  Interpreter = (function() {

    function Interpreter() {
      this.context = new Context();
    }

    Interpreter.prototype.lex = function(code) {
      return new Lexer(code);
    };

    Interpreter.prototype.parse = function(code) {
      return new Parser(new Lexer(code));
    };

    Interpreter.prototype["eval"] = function(code) {
      var cursor;
      cursor = this.parse(code);
      return (new Evaluator(this.context)).run(cursor);
    };

    return Interpreter;

  })();

  module.exports = Interpreter;

}).call(this);
