// Generated by CoffeeScript 1.3.3
(function() {
  var Context, Interpreter, Lexer, Parser;

  Context = require('./context');

  Lexer = require('./lexer');

  Parser = require('./parser');

  Interpreter = (function() {

    function Interpreter() {
      this.context = new Context();
    }

    Interpreter.prototype.lex = function(code) {
      return new Lexer(code);
    };

    Interpreter.prototype.parse = function(code) {
      return new Parser(new Lexer(code));
    };

    Interpreter.prototype["eval"] = function(code) {
      return this.context.myvar = "1";
    };

    return Interpreter;

  })();

  module.exports = Interpreter;

}).call(this);
