// Generated by CoffeeScript 1.3.3
(function() {
  var middleware, path;

  path = require('path');

  middleware = function(express) {
    return express["static"](path.join(__dirname, '/../public'));
  };

  module.exports = middleware;

}).call(this);
