// Generated by CoffeeScript 1.3.3
(function() {
  var read;

  read = function(lexer) {
    var r, subject, t;
    subject = null;
    t = lexer.next();
    while ((t != null) && t.type === 'linefeed') {
      t = lexer.next();
    }
    if (t == null) {
      return null;
    }
    if (t.type === 'symbol') {
      subject = t;
      t = lexer.next();
      if (t.type === 'operator' && t.token === '=') {
        r = read(lexer);
        return {
          type: 'assignment',
          symbol: subject.token,
          node: r
        };
      }
    } else if (t.type === 'literal') {
      subject = t;
      return {
        type: t.type,
        value: t.value
      };
    }
  };

  module.exports.read = read;

}).call(this);
